FROM archlinux:base-devel

RUN pacman -Syu --noconfirm && pacman -S --needed --noconfirm sudo

COPY . /root/.config/nvim

RUN chmod +x /root/.config/nvim/setups/setup-arch.sh && \
    /root/.config/nvim/setups/setup-arch.sh

SHELL ["bash"]
